CREATE TABLE  "INFO"   
   (    "CONTACTNO" NUMBER,   
    "NAME" VARCHAR2(40),   
    "INFO" VARCHAR2(40),   
    "GRADE" VARCHAR2(40),   
     CONSTRAINT "INFO_PK" PRIMARY KEY ("CONTACTNO") ENABLE  
   )  
/  